/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background':                '#f8f9fc',
        'surface':                   '#ffffff',
        'surface-container':         '#f1f3f7',
        'surface-container-low':     '#f5f6f9',
        'surface-container-high':    '#e8eaef',
        'surface-container-highest': '#dde0e6',
        'surface-variant':           '#e0e3e9',
        'on-background':             '#1a1d2e',
        'on-surface':                '#1a1d2e',
        'on-surface-variant':        '#4a5068',
        'primary':                   '#0891b2',
        'primary-fixed':             '#22d3ee',
        'primary-fixed-dim':         '#06b6d4',
        'primary-container':         '#a5f3fc',
        'on-primary':                '#ffffff',
        'on-primary-fixed':          '#083344',
        'on-primary-container':      '#155e75',
        'secondary':                 '#475569',
        'secondary-container':       '#e2e8f0',
        'on-secondary':              '#ffffff',
        'outline':                   '#94a3b8',
        'outline-variant':           '#cbd5e1',
        'error':                     '#dc2626',
        'error-container':           '#fef2f2',
        'tertiary':                  '#d97706',
        'tertiary-container':        '#fef3c7',
      },
      borderRadius: { DEFAULT:'0.125rem', lg:'0.25rem', xl:'0.5rem', full:'0.75rem' },
      fontFamily: {
        'space':    ['Space Grotesk', 'sans-serif'],
        'inter':    ['Inter', 'sans-serif'],
        'headline-md': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
        'display-xl':  ['Space Grotesk'],
        'body-md':     ['Inter'],
        'body-lg':     ['Inter'],
        'label-sm':    ['Inter'],
        'data-mono':   ['Inter'],
      },
      fontSize: {
        'display-xl':  ['48px', { lineHeight:'1.1', letterSpacing:'-0.02em', fontWeight:'700' }],
        'headline-lg': ['32px', { lineHeight:'1.2', fontWeight:'600' }],
        'headline-md': ['24px', { lineHeight:'1.3', fontWeight:'500' }],
        'body-lg':     ['18px', { lineHeight:'1.6', fontWeight:'400' }],
        'body-md':     ['16px', { lineHeight:'1.5', fontWeight:'400' }],
        'data-mono':   ['14px', { lineHeight:'1.4', letterSpacing:'-0.01em', fontWeight:'500' }],
        'label-sm':    ['13px', { lineHeight:'1',   letterSpacing:'0.05em',  fontWeight:'600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
